### ISSUE TITLE
Exception caught during device presence processing

### ISSUE THREAD

**Issue by murinicanor** [dkopecek/usbguard#119]
Hi,

with 0.5.13 i get:
<pre>
Aug 17 20:27:19 tekla systemd[1]: Started USBGuard daemon.
Aug 17 20:27:19 tekla usbguard-daemon[2084]: [2016-08-17 20:27:19.505463] error: Exception caught during device presence processing: /sys/devices/pci0000:00/0000:00:1d.0/usb1/1-1/1-1.3/1-1.3.3: BUG: No descriptor type handler selected in USBDescriptorParser::parse
Aug 17 20:27:19 tekla usbguard-daemon[2084]: [2016-08-17 20:27:19.505953] error: Exception caught during device presence processing: /sys/devices/pci0000:00/0000:00:1d.0/usb1/1-1/1-1.6: BUG: No descriptor type handler selected in USBDescriptorParser::parse
Aug 17 20:27:19 tekla usbguard-daemon[2084]: [2016-08-17 20:27:19.506282] error: Exception caught during device presence processing: /sys/devices/pci0000:00/0000:00:1d.0/usb1/1-1/1-1.7: BUG: No descriptor type handler selected in USBDescriptorParser::parse
</pre>
this is not the case if i use 0.5.11

thanks!

**Comment by dkopecek** [comment]
Thanks for reporting this! I'll make one more bugfix release.

Would be nice to have some use case testing to catch these bugs before a release. That will probably require running a VM and simulating USB devices. I'll add that to my TODO list :-)
