### ISSUE TITLE
usbguard-applet-qt debuginfo inconsistencies

### ISSUE THREAD

**Issue by genodeftest** [dkopecek/usbguard#129]
the usbguard copr, https://copr.fedorainfracloud.org/coprs/mildew/usbguard/, provides an (old, version 0.3.3) debuginfo package for usbguard-applet-qt, whereas there are no new versions of usbguard-applet-qt-debuginfo in both this copr repo and Fedora's updates / updates-testing repos. This is inconsistent and leads to incorrectly installing 0.3.3 debuginfo files when running `dnf debuginfo-install usbguard-applet-qt`.

Please do either of these:
* make `usbguard-debuginfo` obsolete `usbguard-applet-qt-debuginfo`
* split usbguard debuginfo files back to 2 packages, `usbguard-applet-qt-debuginfo` and `usbguard-debuginfo`
* remove the old `usbguard-applet-qt-debuginfo` files from your copr repo

**Comment by dkopecek** [comment]
Thanks for the detailed report. I've deleted the package.
