### ISSUE TITLE
soname version

### ISSUE THREAD

**Issue by murinicanor** [dkopecek/usbguard#132]
shouldn't there be soname version changes between 0.x and 0.y releases of libusbguard?

**Comment by dkopecek** [comment]
Hi, I plan to start with maintaining the version once the project hits the first stable version 1.0.0. However, if you think it would be useful to start earlier with this, I'll reconsider original plan.

**Comment by murinicanor** [comment]
it would help me with packaging for debian, because i'll have to provide different soname versions for the shared library package- but i can understand if it has nor priority at the moment. i can also try to find out how to set the soname myself while building the package (i guess the LT_* variables are what i'm looking for)

**Comment by murinicanor** [comment]
hi, i've repackaged usbguard for debian and moved the shared library to a private dir (and removed the -dev package for now) so this is not an issue any more ;)
