### ISSUE TITLE
[COPR repo] update to usbguard 0.6.3 breaks rules.conf path

### ISSUE THREAD

**Issue by genodeftest** [dkopecek/usbguard#149]
With the Fedora 25 official usbguard-0.6.2-1.fc25 package, the file `/etc/usbguard/usbguard-daemon.conf`contained this line:
```
RuleFile=/etc/usbguard/rules.conf
```
but after updating to 0.6.3-0.1.1483094323.fc25 from mildew/usbguard COPR, it changed to
```
RuleFile=/usr/local/etc/usbguard/rules.conf
```
so it looks like the expansion of %sysconfdir% broke.

**Comment by dkopecek** [comment]
Thanks for the report! I've submitted a new copr build which should fix the issue.
