### ISSUE TITLE
Remove "Qt Applet" From Name

### ISSUE THREAD

**Issue by indolering** [dkopecek/usbguard#164]
The user does not need to know that you are using the QT framework nor that the GUI just passes messages to a daemon ; ).

**Comment by dkopecek** [comment]
Hi, I'm not sure how to interpret this request. Are you talking about the values in [usbguard-applet-qt.desktop.in](https://github.com/dkopecek/usbguard/blob/master/src/GUI.Qt/usbguard-applet-qt.desktop.in)? I'm ok with changing that. What new values do you suggest?

**Comment by indolering** [comment]
>  Are you talking about the values in usbguard-applet-qt.desktop.in? I'm ok with changing that.

Maybe?

> What new values do you suggest?

"USBGuard" - assume users don't know what QT or Applet even mean.
