### ISSUE TITLE
using localtime(time_range) feature

### ISSUE THREAD

**Issue by simakhan785** [dkopecek/usbguard#167]
I try to use the localtime(time_range) feature in rule condition for e.g.- allow id <vendorid:deviceid> if localtime(11:11-16:16); but the rule does not work. The device is always blocked. Basically, how can I construct a rule for a USB for a time range for e.g. btw. 11:10 to 16:11.

Please reply asap.

**Comment by dkopecek** [comment]
Hi, your rule is correct but there's a but in processing of the condition. I'll fix that in a moment. Thanks for reporting!
