### ISSUE TITLE
usbguard does not start with read-only /etc

### ISSUE THREAD

**Issue by murinicanor** [dkopecek/usbguard#191]
From the debian BTS (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=868160)
> usbguard daemon does not start when /etc is placed on read-only filesystem as it
> tries to open /etc/usbguard/usbguard-daemon.conf with rw permissions and
> terminates if it cannot do that.
> As usbguard remains useable without the ability to write to usbguard-daemon.conf
> it should try to open this file in ro mode instead of terminating if opening in
> rw mode fails.

**Comment by dkopecek** [comment]
Thanks for reporting! Fixed in 2f60391fc03b204380e9e87c4c1022fa48198ac2.
