### ISSUE TITLE
A chance for Windows binarys?

### ISSUE THREAD

**Issue by beerisgood** [dkopecek/usbguard#193]
Did exist a chance to make that great stuff works in Windows?

**Comment by dkopecek** [comment]
Hi. If there's support for USB device authorization in the Windows kernel, then it should be possible to implement support for Windows. However, I'm not familiar with the Windows kernel nor the APIs available on Windows, so I won't implement this myself.

**Comment by ghost** [comment]
For future reference, https://github.com/USBShield/USBShield works on Windows at least on my case
