### ISSUE TITLE
Adding users

### ISSUE THREAD

**Issue by MatejKovacic** [dkopecek/usbguard#202]
Hi,

on redme.md you have stated, that you can add users who are allowed to run USBGuard Qt Applet by command:
usbguard add-user joe --devices ALL --exceptions ALL

I have usbguard 0.6.2 on Ubuntu Zesty and this command does not work. Anyway, I have edited /etc/usbguard/usbguard-daemon.conf to add user who can control Qt applet.

**Comment by dkopecek** [comment]
Hi, the README.md you see on the landing page of the repo always refers to the latest version of the sources (master). The `add-user` is available since 0.7.0 as described in the [ChangeLog](https://github.com/dkopecek/usbguard/blame/master/CHANGELOG.md#L43).
