### ISSUE TITLE
append-rule syntax RuleParserError

### ISSUE THREAD

**Issue by dx486** [dkopecek/usbguard#205]
I want to allow some USB devices but I cannot use append-rule option.

What is the correct way of using "append-rule"?

I receive the following error (replaced some chars with "9"):

```
$ sudo usbguard append-rule 'id 9999:9999 serial "" name "USB3.0 Hub             " hash "999999999999999999999999999999999999999ug3Q="'
IPC ERROR: request id=1: IPC method: usbguard.IPC.appendRule: RuleParserError

```

Please consider adding an example for the correct way of using append-rule in the documentation.

usbguard version: 0.6.2+ds1-2
OS: debian 9

**Comment by dkopecek** [comment]
The rule is missing the `target` part: allow, block or reject. It should be specified as the first thing in a rule and is actually the only part that is not optional.

So given your example:

$ sudo usbguard append-rule 'id 9999:9999 serial "" name "USB3.0 Hub             " hash "999999999999999999999999999999999999999ug3Q="'

Change that to:

$ sudo usbguard append-rule '**allow** id 9999:9999 serial "" name "USB3.0 Hub             " hash "999999999999999999999999999999999999999ug3Q="'

(assuming you want to allow the device)

**Comment by dx486** [comment]
Oh... How I have missed that... Thank you very much for your quick reply & solution.
