### ISSUE TITLE
usbguard-daemon cannot detect libsodium.so.18

### ISSUE THREAD

**Issue by regginator729** [dkopecek/usbguard#208]
Currently using Arch. usbguard doesn't seem to work (`IPC connect: service=usbguard, connection refused`), and when running `usbguard-dbus` or `usbguard-daemon` in terminal, the following error occurs:

`usbguard-dbus: error while loading shared libraries: libsodium.so.18: cannot open shared object file: No such file or directory`

The simplest way to fix this is to copy `libsodium.so.18` from `libsodium-1.0.14-1-x86_64.pkg.tar.xz` from the Arch Linux archive to `/usr/lib/`, but that would seem to be a dirty fix. Is there a way for `usbguard` to be "independent" from the version of the libraries?

**Comment by dkopecek** [comment]
Hi. I think this is a packaging problem. Did you compile the package by yourself? It looks like it was compiled against a different version of libsodium than what is available from the repository.
