### ISSUE TITLE
[RFE] Randomize the position of the device dialog window

### ISSUE THREAD

**Issue by dkopecek** [dkopecek/usbguard#55]
_From @dkopecek on February 7, 2016 10:27_

~~Shuffling the order of the buttons~~ Randomizing the window position could help in a situation where an attacker has some sort of automated control over an already authorized pointing device (e.g. a mouse, or even a wireless one -- in that case it's possible to operate it remotely by sending commands using the wireless protocol). ~~If the buttons are shuffled~~ If the position of the window is randomized, the attacker can't automate the attack using known button positions.

The feature should be configurable in the interface.

_Copied from original issue: dkopecek/usbguard-applet-qt#9_

**Comment by rebecca-palmer** [comment]
It might be easier and/or more user-friendly to randomize the overall window position instead.

**Comment by dkopecek** [comment]
The referenced commit adds and initial implementation of the position randomization (enabled by default). However, it needs testing and probably some additional work as it seems that it won't work for all environments. I'm using i3 (an older release) and it doesn't work. Probably because i3 overrides the window position when switching the window to a floating type -- just guessing.

**Comment by dkopecek** [comment]
Seems to be working with newer i3 and also in KDE 5.

**Comment by indolering** [comment]
In what threat model does an attacker have control of the pointer but no control of the keyboard input?
