### ISSUE TITLE
[Copr] Fedora 24 package broken due to libsodium soname bump

### ISSUE THREAD

**Issue by genodeftest** [dkopecek/usbguard#66]
I currently cannot install usbguard 0.5 from [your copr](https://copr.fedorainfracloud.org/coprs/mildew/usbguard/) due to a soname version bump in libsodium. usbguard requires libsodium.so.13 (which is available in F23), but libsodium on F24 was bumped to libsodium.so.18.

**Comment by dkopecek** [comment]
Thanks for letting me know. I've submitted a new build: https://copr.fedorainfracloud.org/coprs/mildew/usbguard/build/172208/

**Comment by dkopecek** [comment]
Hmm, looks like I forgot to update the BuildRequires. I'll submit another one in a minute.

**Comment by dkopecek** [comment]
Unfortunately, there's a "cloud outage" at the moment and copr is not responding...

**Comment by dkopecek** [comment]
https://copr.fedorainfracloud.org/coprs/mildew/usbguard/build/172212/

**Comment by genodeftest** [comment]
Works fine, thank you!
