### ISSUE TITLE
Sign releases (and maybe commits and tags)

### ISSUE THREAD

**Issue by murinicanor** [dkopecek/usbguard#84]
It would be great if you could gpg-sign your releases (https://wiki.debian.org/Creating%20signed%20GitHub%20releases) - i could then use the debian watch file to do signature verification (https://wiki.debian.org/debian/watch#Cryptographic_signature_verification)

**Comment by dkopecek** [comment]
Hi and thanks for this suggestion. I'll start signing releases starting with the next release (0.5). I'll sign also tags (but so far I'm tagging only the releases...). I'll leave this open until the 0.5 release.

**Comment by dkopecek** [comment]
Started signing commits since 9ea57056dc060dce9de4344629fe63cb28732ec9. My PGP keyid is [B25991BC](https://keys.fedoraproject.org/pks/lookup?search=0xB25991BC&fingerprint=on&hash=on&op=index).

**Comment by dkopecek** [comment]
Released 0.5.10 including a signed tag and tarball.
