### ISSUE TITLE
usbguard-qt-applet crashes when usbguard disappears

### ISSUE THREAD

**Issue by murinicanor** [dkopecek/usbguard#96]
the usbguard-qt-applet crashes with:
`terminate called after throwing an instance of 'usbguard::IPCException'
  what():  Receive error
[1]    4500 abort      usbguard-applet-qt
`
if the service disappears. i think it should just show some kind of warning and go into a 'disabled' state

**Comment by dkopecek** [comment]
Yes, it should go into the "IPC disconnected state" and try to reconnect. This should be an easy fix. I'll look into the GUI issues during the next week. Thanks for the report.
