### ISSUE TITLE
use released version of pegtl

### ISSUE THREAD

**Issue by murinicanor** [dkopecek/usbguard#98]
hi,

thanks for the move to pegtl! so, there is a small problem i'm not sure how to handle: were you aware that you're using a unreleased version of pegtl? there is pegtl 1.3.1, which is what i uploaded to debian, but the ruleparser is already using `pegtl::action_input` which was introduced to pegtl in a commit (colinh/PEGTL@010e2f46176667e85a88326a75f3bbac13de63b7) after the 1.3.1 release...
if thats on purpose, i'll ask the pegtl maintainers when there will be a release including those changes, but i guess i won't be able to upload an unreleased version if they do releases...

(on the other hand, that commit of pegtl seems to break backwards compatibility, because pegt::input becomes to pegtl::action_input)

cheers,
muri

**Comment by dkopecek** [comment]
Hello. Thanks, I'll look into it. I've packaged the released version of PEGTL for Fedora so I'll have the same problem when updating to the next usbguard release.
